/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AArrayrefPrimary2 extends PPrimary2
{
    private PArrayref _arrayref_;

    public AArrayrefPrimary2()
    {
        // Constructor
    }

    public AArrayrefPrimary2(
        @SuppressWarnings("hiding") PArrayref _arrayref_)
    {
        // Constructor
        setArrayref(_arrayref_);

    }

    @Override
    public Object clone()
    {
        return new AArrayrefPrimary2(
            cloneNode(this._arrayref_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayrefPrimary2(this);
    }

    public PArrayref getArrayref()
    {
        return this._arrayref_;
    }

    public void setArrayref(PArrayref node)
    {
        if(this._arrayref_ != null)
        {
            this._arrayref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayref_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrayref_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrayref_ == child)
        {
            this._arrayref_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrayref_ == oldChild)
        {
            setArrayref((PArrayref) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
