/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ABlankPrivacy extends PPrivacy
{

    public ABlankPrivacy()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ABlankPrivacy();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlankPrivacy(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
