/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AExprExpr20 extends PExpr20
{
    private PExpr30 _expr30_;

    public AExprExpr20()
    {
        // Constructor
    }

    public AExprExpr20(
        @SuppressWarnings("hiding") PExpr30 _expr30_)
    {
        // Constructor
        setExpr30(_expr30_);

    }

    @Override
    public Object clone()
    {
        return new AExprExpr20(
            cloneNode(this._expr30_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprExpr20(this);
    }

    public PExpr30 getExpr30()
    {
        return this._expr30_;
    }

    public void setExpr30(PExpr30 node)
    {
        if(this._expr30_ != null)
        {
            this._expr30_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr30_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr30_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr30_ == child)
        {
            this._expr30_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr30_ == oldChild)
        {
            setExpr30((PExpr30) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
