/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import java.util.*;
import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AListArglist extends PArglist
{
    private PExpr _expr_;
    private final LinkedList<PArg> _arg_ = new LinkedList<PArg>();

    public AListArglist()
    {
        // Constructor
    }

    public AListArglist(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") List<PArg> _arg_)
    {
        // Constructor
        setExpr(_expr_);

        setArg(_arg_);

    }

    @Override
    public Object clone()
    {
        return new AListArglist(
            cloneNode(this._expr_),
            cloneList(this._arg_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListArglist(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public LinkedList<PArg> getArg()
    {
        return this._arg_;
    }

    public void setArg(List<PArg> list)
    {
        this._arg_.clear();
        this._arg_.addAll(list);
        for(PArg e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._arg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._arg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        for(ListIterator<PArg> i = this._arg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
