/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class APrimaryArrayref extends PArrayref
{
    private PPrimary2 _primary2_;
    private TLbrack _lbrack_;
    private PExpr _expr_;
    private TRbrack _rbrack_;

    public APrimaryArrayref()
    {
        // Constructor
    }

    public APrimaryArrayref(
        @SuppressWarnings("hiding") PPrimary2 _primary2_,
        @SuppressWarnings("hiding") TLbrack _lbrack_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TRbrack _rbrack_)
    {
        // Constructor
        setPrimary2(_primary2_);

        setLbrack(_lbrack_);

        setExpr(_expr_);

        setRbrack(_rbrack_);

    }

    @Override
    public Object clone()
    {
        return new APrimaryArrayref(
            cloneNode(this._primary2_),
            cloneNode(this._lbrack_),
            cloneNode(this._expr_),
            cloneNode(this._rbrack_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimaryArrayref(this);
    }

    public PPrimary2 getPrimary2()
    {
        return this._primary2_;
    }

    public void setPrimary2(PPrimary2 node)
    {
        if(this._primary2_ != null)
        {
            this._primary2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primary2_ = node;
    }

    public TLbrack getLbrack()
    {
        return this._lbrack_;
    }

    public void setLbrack(TLbrack node)
    {
        if(this._lbrack_ != null)
        {
            this._lbrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lbrack_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TRbrack getRbrack()
    {
        return this._rbrack_;
    }

    public void setRbrack(TRbrack node)
    {
        if(this._rbrack_ != null)
        {
            this._rbrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rbrack_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primary2_)
            + toString(this._lbrack_)
            + toString(this._expr_)
            + toString(this._rbrack_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primary2_ == child)
        {
            this._primary2_ = null;
            return;
        }

        if(this._lbrack_ == child)
        {
            this._lbrack_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._rbrack_ == child)
        {
            this._rbrack_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primary2_ == oldChild)
        {
            setPrimary2((PPrimary2) newChild);
            return;
        }

        if(this._lbrack_ == oldChild)
        {
            setLbrack((TLbrack) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._rbrack_ == oldChild)
        {
            setRbrack((TRbrack) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
