/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AExprExpr40 extends PExpr40
{
    private PExpr50 _expr50_;

    public AExprExpr40()
    {
        // Constructor
    }

    public AExprExpr40(
        @SuppressWarnings("hiding") PExpr50 _expr50_)
    {
        // Constructor
        setExpr50(_expr50_);

    }

    @Override
    public Object clone()
    {
        return new AExprExpr40(
            cloneNode(this._expr50_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprExpr40(this);
    }

    public PExpr50 getExpr50()
    {
        return this._expr50_;
    }

    public void setExpr50(PExpr50 node)
    {
        if(this._expr50_ != null)
        {
            this._expr50_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr50_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr50_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr50_ == child)
        {
            this._expr50_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr50_ == oldChild)
        {
            setExpr50((PExpr50) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
