/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AGeExpr40 extends PExpr40
{
    private PExpr40 _left_;
    private TGe _ge_;
    private PExpr50 _right_;

    public AGeExpr40()
    {
        // Constructor
    }

    public AGeExpr40(
        @SuppressWarnings("hiding") PExpr40 _left_,
        @SuppressWarnings("hiding") TGe _ge_,
        @SuppressWarnings("hiding") PExpr50 _right_)
    {
        // Constructor
        setLeft(_left_);

        setGe(_ge_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AGeExpr40(
            cloneNode(this._left_),
            cloneNode(this._ge_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGeExpr40(this);
    }

    public PExpr40 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpr40 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TGe getGe()
    {
        return this._ge_;
    }

    public void setGe(TGe node)
    {
        if(this._ge_ != null)
        {
            this._ge_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ge_ = node;
    }

    public PExpr50 getRight()
    {
        return this._right_;
    }

    public void setRight(PExpr50 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._ge_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._ge_ == child)
        {
            this._ge_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpr40) newChild);
            return;
        }

        if(this._ge_ == oldChild)
        {
            setGe((TGe) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpr50) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
