/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AIconstPrimary2 extends PPrimary2
{
    private TIconst _iconst_;

    public AIconstPrimary2()
    {
        // Constructor
    }

    public AIconstPrimary2(
        @SuppressWarnings("hiding") TIconst _iconst_)
    {
        // Constructor
        setIconst(_iconst_);

    }

    @Override
    public Object clone()
    {
        return new AIconstPrimary2(
            cloneNode(this._iconst_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIconstPrimary2(this);
    }

    public TIconst getIconst()
    {
        return this._iconst_;
    }

    public void setIconst(TIconst node)
    {
        if(this._iconst_ != null)
        {
            this._iconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iconst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iconst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iconst_ == child)
        {
            this._iconst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iconst_ == oldChild)
        {
            setIconst((TIconst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
