/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import java.util.*;
import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AType extends PType
{
    private TId _id_;
    private final LinkedList<PEmptydim> _emptydim_ = new LinkedList<PEmptydim>();

    public AType()
    {
        // Constructor
    }

    public AType(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PEmptydim> _emptydim_)
    {
        // Constructor
        setId(_id_);

        setEmptydim(_emptydim_);

    }

    @Override
    public Object clone()
    {
        return new AType(
            cloneNode(this._id_),
            cloneList(this._emptydim_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAType(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PEmptydim> getEmptydim()
    {
        return this._emptydim_;
    }

    public void setEmptydim(List<PEmptydim> list)
    {
        this._emptydim_.clear();
        this._emptydim_.addAll(list);
        for(PEmptydim e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._emptydim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._emptydim_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PEmptydim> i = this._emptydim_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PEmptydim) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
